name: Greetings

on: [pull_request, issues, push]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: "docker://cirrusactions/email:latest"
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: '恭喜你啊，创建了第一个issue'
        pr-message: 'Message that will be displayed on users'' first pr'
        
  
